# Site Settings
name: HackHerWay Cybersecurity
title: HackHerWay | A blog for all things Cybersecurity
description: Learn How to HackHerWay | The Hacker Way
tags:
  - hacking-tutorials
  - network-security
  - hacking-tools
  - resource-guides
  - cyberattacks
show_hero: true
menu:
  - title: 127.0.0.1
    url: /
  - title: WHOAMI
    url: /whoami
  - title: Ethical Hacking
    url: /ethical-hacking
  - title: Computer Networks Concepts
    url: /computer-network-concepts
  - title: /Hacking Essentials
    url: /hacking-essentials
    submenu:
      - title: Hacking Methodology
        url: hacking-methodology
  - title: Hacking Tools
    url: /hacking-tools
    submenu:
      - title: Windows Hacking Tools
        url: /windows-hacking-tools
  - title: Information Security
    url: information-security
  - title: OSINT
    url: /osint
  - title: Cyberattacks
    url: cyberattacks
  - title: Tutorials
    url: /tutorials
  -
email: mindhackdiva@pm.me
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id


# Social Media Settings
# Remove the item if you don't need it
github_username: d0midigi
# facebook_username: facebook_username
twitter_username: d0midigi
instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  "docs/",
  "vendor/",
  "LICENSE",
  "CHANGELOG.md",
  "jekflix.gemspec",
  "package.json",
  "package-lock.json",
  "src",
  "node_modules",
  "initpost.sh",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "README.md"
]

# Theme
version: v3.1.2
