name: HackHerWay
title: HackHerWay | An ethical hacking and cybersecurity space
description: Learn How to HackHerWay - The Hacker Way!
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: 127.0.0.1
    url: /
  - title: WHOAMI
    url: /about
  - title: Hacking Tools
    url: /contact
  - title: Feed
    url: /feed.xml
email: mindhackdiva@pm.me
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
